CREATE TABLE TECNICO_AGRICOLA
(
     CPF VARCHAR(11) NOT NULL,
     NOME VARCHAR(50) NOT NULL,
     NUMERO_REGISTRO VARCHAR(20) NOT NULL,
     CONSTRAINT PK_TECNICO_AGRICOLA PRIMARY KEY(NUMERO_REGISTRO)
 );